# Use root/example as user/password credentials
version: '3.4'

# Docker for local use

services:
  html2pdf-saas:
    image: wyzenrepo/php-fpm74:latest

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.html2pdf-saas-http.rule=Host(`html2pdf.docker.localhost`)"
      - "traefik.http.routers.html2pdf-saas-http.entrypoints=web"

    expose:
      - 80

    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
