# Use root/example as user/password credentials
version: '3.4'

# Docker for local use

services:
  html2pdf-saas:
    image: wyzenrepo/html2pdf:pdfmyurl
    container_name: html2pdf-saas
    restart: always
    env_file:
      - ./docker-compose.env

    volumes:
      - ./application/data:/data

    expose:
      - 80

    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
